In [ ]:
# svr, 2.023 SVR, try with normalisation with svr, difference in accuracy, linear, poly, rbf, sigmoid,
# correcting the salary, treat outlier and check difference, svr kernel trick, 2.024 kernel trick linear and poly
# svc kernel trick, which kernel fits better for male female

# Imports

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats
%matplotlib inline

In [ ]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score
from sklearn.svm import SVR
from sklearn.metrics import accuracy_score
from sklearn.metrics import mean_squared_error
from sklearn.preprocessing import StandardScaler

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
filepath = "/content/drive/MyDrive/Six_Schools.xlsx"
df = pd.ExcelFile(filepath)

In [ ]:
filepath = "/content/drive/MyDrive/Classroom/ML_NMKRV/Students/Meghna/Six_Schools.xlsx"
df = pd.ExcelFile(filepath)

#Prepping Dataset

In [ ]:
df_puma = df.parse('Puma_Indian')
df_puma.head()

Height_cm  Weight_Kg  Age  male Sex  Unnamed: 5  Unnamed: 6  Unnamed: 7  \
0    53.9750   4.252425  0.0     0   F         NaN      53.975         NaN   
1    55.8800   4.847765  0.0     0   F         NaN     179.070         NaN   
2    56.5150   5.159609  0.0     0   F         NaN         NaN         NaN   
3    59.6138   5.896696  1.0     0   F         NaN         NaN         NaN   
4    60.4520   5.669900  1.0     1   M         NaN         NaN         NaN   

   ht_bin  
0    50.0  
1    60.0  
2    70.0  
3    80.0  
4    90.0

In [ ]:
df_puma = df_puma.drop(df_puma[['Unnamed: 5',	'Unnamed: 6',	'Unnamed: 7',	'ht_bin']], axis = 1)

In [ ]:
df_puma.tail()

Height_cm  Weight_Kg   Age  male Sex
539   171.1198  56.557252  37.0     1   M
540   171.4500  56.557252  52.0     1   M
541   172.7200  61.801910  22.0     1   M
542   172.9994  51.255896  38.0     1   M
543   179.0700  55.706767  23.0     1   M

In [ ]:
df_puma = pd.DataFrame(df_puma)

In [ ]:
true_bmi = lambda row: row['Weight_Kg'] / ((row['Height_cm'] / 100) ** 2)

In [ ]:
df_puma['BMI'] = df_puma.apply(true_bmi, axis = 1)

In [ ]:
df_puma.sample(5)

Height_cm  Weight_Kg   Age  male Sex        BMI
356   153.6700  44.565414  54.0     0   F  18.872080
521   167.0050  47.173568  30.0     1   M  16.913745
106   114.3000  19.050864   7.0     1   M  14.582172
132   124.4600  18.257078  12.0     0   F  11.786142
302   150.1648  41.957260  22.0     0   F  18.606763

# SVR using Puma Indians (not normalised)

## kernel: rbf

In [ ]:
X = df_puma[['Height_cm', 'Weight_Kg', 'Age', 'male']]
y = df_puma['BMI']

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
svr_model = SVR(kernel='rbf')

In [ ]:
svr_model.fit(X, y)

SVR()

In [ ]:
y_pred = svr_model.predict(X_test)

In [ ]:
y_pred[:5]

array([18.94269565, 17.64678089, 17.8034506 , 20.54774225, 18.98940053])

In [ ]:
mse = mean_squared_error(y_test, y_pred)
print("Mean Squared Error:", mse)

Mean Squared Error: 1.4025527326723324


## kernel: linear

In [ ]:
svr_model = SVR(kernel='linear')

In [ ]:
svr_model.fit(X, y)

SVR(kernel='linear')

In [ ]:
y_pred = svr_model.predict(X_test)

In [ ]:
y_pred[:5]

array([18.67810207, 18.38560859, 17.54049719, 21.73380746, 18.14843605])

In [ ]:
mse = mean_squared_error(y_test, y_pred)
print("Mean Squared Error:", mse)

Mean Squared Error: 0.5966616816479361


## kernel: sigmoid

In [ ]:
svr_model = SVR(kernel = 'sigmoid')

In [ ]:
svr_model.fit(X, y)

SVR(kernel='sigmoid')

In [ ]:
y_pred = svr_model.predict(X_test)

In [ ]:
y_pred[:5]

array([15.15728462, 18.26479341, 17.00177107, 13.1193963 , 12.42203873])

In [ ]:
mse = mean_squared_error(y_test, y_pred)
print("Mean Squared Error:", mse)

Mean Squared Error: 87.19229550279188


## kernel: poly

In [ ]:
svr_model = SVR(kernel = 'poly')

In [ ]:
svr_model.fit(X, y)

SVR(kernel='poly')

In [ ]:
y_pred = svr_model.predict(X_test)

In [ ]:
y_pred[:5]

array([19.02371935, 17.41802486, 17.50999255, 22.54759544, 19.41493154])

In [ ]:
mse = mean_squared_error(y_test, y_pred)
print("Mean Squared Error:", mse)

Mean Squared Error: 1.5584119459735217


# SVR using Puma Indians (normalised)



## Kernel: rbf


In [ ]:
X = df_puma[['Height_cm', 'Weight_Kg', 'Age', 'male']]
y = df_puma['BMI']

In [ ]:
scaler = StandardScaler()
X_normalized = scaler.fit_transform(X)

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X_normalized, y, test_size=0.2, random_state=42)

In [ ]:
svr_rbf = SVR(kernel='rbf')

In [ ]:
svr_rbf.fit(X_train, y_train)

SVR()

In [ ]:
y_pred_rbf = svr_rbf.predict(X_test)

In [ ]:
y_pred_rbf[:6]

array([18.98050632, 17.55247865, 18.0869625 , 20.51933721, 19.20997871,
       14.21786332])

In [ ]:
mse = mean_squared_error(y_test, y_pred_rbf)
print("Mean Squared Error:", mse)

Mean Squared Error: 1.6971985863061951


In [ ]:
sample = df_puma.sample()
y_pred = svr_rbf.predict(sample[['Height_cm','Weight_Kg','Age','male']])
print(f"\n{sample}\n\npredicted BMI: {y_pred}\n")


     Height_cm  Weight_Kg   Age  male Sex        BMI
282    149.225  43.941725  33.0     1   M  19.733037

predicted BMI: [18.39795919]



In [ ]:
df1 = df_puma.copy()

In [ ]:
df1.shape

(544, 6)

In [ ]:
y_hat = svr_rbf.predict(df_puma[['Height_cm', 'Weight_Kg', 'Age', 'male']])

In [ ]:
type(y_hat)

numpy.ndarray

In [ ]:
y_hat.shape

(544,)

In [ ]:
df_puma['y_hat'] = y_hat

In [ ]:
import math

In [ ]:
df_puma.shape

(544, 7)

In [ ]:
import math
df_puma['err_square'] = (df_puma['BMI'] - df_puma['y_hat'])**2
rmse = math.sqrt(df_puma['err_square'].mean())
print(f"\nRMSE with rbf Kernel: {rmse:.4f}")


RMSE with rbf Kernel: 1.2086


## kernel: linear



In [ ]:
X_normalized = X_normalized >= 0

In [ ]:
X_normalized

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       ...,
       [ True,  True, False,  True],
       [ True,  True,  True,  True],
       [ True,  True, False,  True]])

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X_normalized, y, test_size=0.2, random_state=42)

In [ ]:
svr_linear = SVR(kernel = 'linear')

In [ ]:
svr_linear.fit(X_train, y_train)

SVR(kernel='linear')

In [ ]:
X_train

array([[ True, False,  True, False],
       [ True, False, False, False],
       [ True,  True, False, False],
       ...,
       [ True,  True,  True, False],
       [ True,  True,  True,  True],
       [False, False, False,  True]])

In [ ]:
y_pred_linear = svr_linear.predict(X_test)

In [ ]:
y_pred_linear[:5]

array([18.89466995, 18.6408105 , 18.8483135 , 18.89466995, 18.89466995])

In [ ]:
mse_linear = mean_squared_error(y_test, y_pred_linear)
print("Mean Squared Error:", mse_linear)

In [ ]:
sample = df_puma.sample()
y_sample = svr_linear.predict(sample[['Height_cm', 'Weight_Kg', 'Age', 'male']])
print(f"\n{sample}\n\npredicted BMI: {y_sample}\n")


     Height_cm  Weight_Kg   Age  male Sex        BMI     y_hat  err_square
425    158.115  43.147939  63.0     1   M  17.258932  18.38597    1.270215

predicted BMI: [360.67698428]



/usr/local/lib/python3.10/dist-packages/sklearn/base.py:432: UserWarning: X has feature names, but SVR was fitted without feature names
  warnings.warn(


Model throwing up negative predicted BMI.

Reasons:
* negative values
* columns not properly loaded

fixes
* filtered negative values from column and reloaded with cell 145

result
* worked

In [ ]:
y_hat_linear = svr_linear.predict(df_puma[['Height_cm', 'Weight_Kg', 'Age', 'male']])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:432: UserWarning: X has feature names, but SVR was fitted without feature names
  warnings.warn(


In [ ]:
df_puma['y_hat_linear'] = y_hat_linear

In [ ]:
df_puma['err_square'] = (df_puma['BMI'] - df_puma['y_hat_linear'])**2
rmse = math.sqrt(df_puma['err_square'].mean())
print(f"\nRMSE with linear Kernel: {rmse:.4f}")


RMSE with linear Kernel: 298.9553


## kernel: sigmoid

In [ ]:
svr_sigmoid = SVR(kernel = 'sigmoid')

In [ ]:
svr_sigmoid.fit(X_train, y_train)

SVR(kernel='sigmoid')

In [ ]:
y_pred_sigmoid = svr_sigmoid.predict(X_test)

In [ ]:
y_pred_sigmoid[:5]

array([-22.03103582,  23.37600179,  21.05550321, -22.03103582,
       -22.03103582])

In [ ]:
mse_sigmoid = mean_squared_error(y_test, y_pred_sigmoid)
print("Mean Squared Error:", mse_sigmoid)

Mean Squared Error: 1179.7633798005822


In [ ]:
sample = df_puma.sample()
y_sample = svr_sigmoid.predict(sample[['Height_cm', 'Weight_Kg', 'Age', 'male']])
print(f"\n{sample}\n\npredicted BMI: {y_sample}\n")


     Height_cm  Weight_Kg   Age  male Sex        BMI      y_hat    err_square  \
160     135.89   27.21552  15.0     0   F  14.738105  15.230482  68313.882651   

     y_hat_linear  
160    276.107351  

predicted BMI: [18.86177467]



/usr/local/lib/python3.10/dist-packages/sklearn/base.py:432: UserWarning: X has feature names, but SVR was fitted without feature names
  warnings.warn(


In [ ]:
y_hat_sigmoid = svr_sigmoid.predict(df_puma[['Height_cm', 'Weight_Kg', 'Age', 'male']])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:432: UserWarning: X has feature names, but SVR was fitted without feature names
  warnings.warn(


In [ ]:
df_puma['y_hat_sigmoid'] = y_hat_sigmoid

In [ ]:
df_puma['err_square'] = (df_puma['BMI'] - df_puma['y_hat_sigmoid'])**2
rmse = math.sqrt(df_puma['err_square'].mean())
print(f"\nRMSE with sigmoid Kernel: {rmse:.4f}")


RMSE with sigmoid Kernel: 30.8954


## kernel: poly

In [ ]:
svr_poly = SVR(kernel = 'poly')

In [ ]:
svr_poly.fit(X_train, y_train)

SVR(kernel='poly')

In [ ]:
y_pred_poly = svr_poly.predict(X_test)

In [ ]:
y_pred_poly[:5]

array([18.89406717, 18.92592886, 18.70440908, 18.89406717, 18.89406717])

In [ ]:
mse_poly = mean_squared_error(y_test, y_pred_poly)
print("Mean Squared Error:", mse_poly)

Mean Squared Error: 2.7649991985720157


In [ ]:
sample = df_puma.sample()
y_sample = svr_poly.predict(sample[['Height_cm', 'Weight_Kg', 'Age', 'male']])
print(f"\n{sample}\n\npredicted BMI: {y_sample}\n")


    Height_cm  Weight_Kg  Age  male Sex        BMI      y_hat  err_square  \
41      85.09  11.424848  3.0     0   F  15.779506  14.727255    9.527597   

    y_hat_linear  y_hat_sigmoid  
41    161.186442      18.866187  

predicted BMI: [701003.79912054]



/usr/local/lib/python3.10/dist-packages/sklearn/base.py:432: UserWarning: X has feature names, but SVR was fitted without feature names
  warnings.warn(


In [ ]:
y_hat_poly = svr_poly.predict(df_puma[['Height_cm', 'Weight_Kg', 'Age', 'male']])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:432: UserWarning: X has feature names, but SVR was fitted without feature names
  warnings.warn(


In [ ]:
df_puma['y_hat_poly'] = y_hat_poly

In [ ]:
df_puma['err_square'] = (df_puma['BMI'] - df_puma['y_hat_poly'])**2
rmse = math.sqrt(df_puma['err_square'].mean())
print(f"\nRMSE with sigmoid Kernel: {rmse:.4f}")


RMSE with sigmoid Kernel: 3761423.5647


# Difference in accuracy with each kernel

In [ ]:
# comparing rmse
for i in ['rbf', 'linear', 'sigmoid', 'poly']:
    model = SVR(kernel = i)
    model.fit(X, y.ravel())
    y_hat = model.predict(X)

    df1 = df_puma.copy()
    df1['y_hat'] = y_hat
    df1['err_square'] = (df1.BMI - df1.y_hat)**2
    print(f"{i:7}: {math.sqrt(df1.err_square.mean()):.4f}")

rbf    : 1.1009
linear : 0.6515
sigmoid: 8.3564
poly   : 1.1186
